# Version 1.0 - 12/29/2020 by Keith
# Tried to come up with a good name, and got as far as Some News Today...
# In this version, the idea is to run this on your *nix based system using crontab.
# You can also call just the file and it will email immediately.
# Currently this accepts one argument, a search term. If none is provided it will give top 10 news items.

import config, emailfunc, newsfunc
import datetime
import sys
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

message = MIMEMultipart("alternative")
message["Subject"] = "Some News Today - " + datetime.datetime.now().strftime("%A, %B %d")
message["From"] = "Some News Today <"+ config.emailfrom + ">"
message["To"] = config.emailto
qualifier = ""

# Determine if sys arg was set, if so, that is a search term; if not, grab the top-10
if len(sys.argv) > 1:
	data = newsfunc.news_search(config.API_KEY, sys.argv[1], config.language, config.country)
	qualifier = sys.argv[1]
else:
	data = newsfunc.news_top(config.API_KEY, config.language, config.country)
	qualifier = "top" 
	
ndata = json.loads(data)

header = """\
	<html><body>
		<p>Your {} news for today, generated by SomeNewsToday.py:</p>
""".format(qualifier)

footer = """\
	<p>For code and info about this project, please see my Github page here: 
	<a href='https://github.com/novakeith'>Novakeith on Github</a></p>
"""

middle = "<ul>"

for article in ndata["articles"]:
	middle = middle + "<li><p>" + article["title"] + "; Source: <a href='" + article["url"] + "'>" + article["source"]["name"] + "</a></p></li>\n"
	
middle = middle + "</ul>"

entireText = header + middle + footer
htmlencText = MIMEText(entireText, "html")
message.attach(htmlencText)


# finally, send the email:

print(emailfunc.sendemail(config.smtpserver, config.emailfrom, config.emailpass, config.emailto, message, config.smtpport))

print("That's your news for today, see you tomorrow!")
exit()